CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(50));

CREATE TABLE COURSES (
COURSE_ID INT PRIMARY KEY,
COURSE_NAME VARCHAR(50),
DEPARTMENT_ID INT,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(101, 'INFORMATION TECHNOLOGY'),
(102, 'CIVIL ENGINEERING'),
(103, 'CHEMISTRY'),
(104, 'AERONAUTICAL ENGINEERING'),
(105, 'STATISTICS');

INSERT INTO COURSES (COURSE_ID, COURSE_NAME, DEPARTMENT_ID) VALUES
(1001, 'WEB TECHNOLOGIES', 101),
(1002, 'NETWORK SECURITY', 101),
(1003, 'CLOUD COMPUTING', 101),
(1101, 'STRUCTURAL ANALYSIS', 102),
(1102, 'TRANSPORTATION ENGINEERING', 102),
(1201, 'ORGANIC CHEMISTRY', 103),
(1202, 'PHYSICAL CHEMISTRY', 103),
(1301, 'AERODYNAMICS', 104);

INSERT INTO COURSES (COURSE_ID, COURSE_NAME, DEPARTMENT_ID) VALUES
(1302, 'FLIGHT MECHANICS', 104),
(1401, 'PROBABILITY THEORY', 105),
(1402, 'NUMERICAL METHODS', 105);


SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D JOIN COURSES C ON 
D.DEPARTMENT_ID = C.DEPARTMENT_ID
GROUP BY
    D.DEPARTMENT_NAME
HAVING
    COUNT(C.COURSE_ID) >= 2;