CREATE TABLE AUTHORS(
AUTH_ID INT PRIMARY KEY,
AUTH_NAME VARCHAR(50),
COUNTRY VARCHAR(100));

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
BOOK_NAME VARCHAR(50),
AUTH_ID INT,
PUBLISH_YEAR INT);

ALTER TABLE BOOKS
ADD CONSTRAINT fk_books_authors
FOREIGN KEY (AUTH_ID) REFERENCES AUTHORS(AUTH_ID);

INSERT INTO AUTHORS (AUTH_ID,AUTH_NAME,COUNTRY) VALUES
(1,'HARSH KUMAR','INDIA'),
(2,'VARUN SINGH','UNITED STATES'),
(3,'SHIVA KUMAR','UNITED KINGDOM');

INSERT INTO BOOKS (BOOK_ID,BOOK_NAME,AUTH_ID,PUBLISH_YEAR) VALUES
(1001,'LIFE',1,2005),
(1002,'LESSON',2,2007),
(1003,'LEARNING',1,2012),
(1004,'MUSIC',1,2009),
(1005,'ART',3,2003),
(1006,'REALITY',3,2008),
(1007,'ACCEPTANCE',2,2016);

SELECT B.BOOK_ID,B.BOOK_NAME,B.PUBLISH_YEAR,A.AUTH_NAME,A.COUNTRY FROM
AUTHORS A INNER JOIN BOOKS B ON
A.AUTH_ID = B.AUTH_ID;

